### ISSUE TITLE
Error message after erase disk.

### ISSUE THREAD

**Issue by YehudaBialik** [munki/installr#4]
I'm getting an error after the install starts.  Error: An internal error occurred while starting the installer.  I took this installer from the dmg that I put, and have used many times, in munki server.  Could that be part of the problem?

![img_20181031_125544](https://user-images.githubusercontent.com/9950079/47807618-eff8a600-dd12-11e8-8668-88f4b3a47a44.jpg)

**Comment by gregneagle** [comment]
This is all Apple code running at this point. Look at /var/log/install.log for clues. It could also be one or more of the included packages. I specifically suspect the munkitools* packages since it looks like you've extracted the component packages and `startosinstall` requires distribution-style (AKA "product archive") packages.

**Comment by gregneagle** [comment]
https://github.com/munki/installr/blob/master/README.md#packages

**Comment by YehudaBialik** [comment]
These are the same packages I'm using successfully with bootstrappr.  I guess I incorrectly assumed they would work here also.  I'll switch out the munki packages and see what happens.  Thanks.

**Comment by gregneagle** [comment]
bootstrappr uses `/usr/sbin/installer` to install packages.
installr adds extra packages as additional `--installpackage` arguments to `startosinstall`. Therefore you must play by `startosinstall`'s more restrictive rules. I'm going to close this -- feel free to reopen if there is more to this issue.
